### What is numpy

* Numpy stands for numerical python.
* It is used to perform diff Mathematical operation On N-Dimentional Array.
* A Numpy array is a Homogeneous Data type array which means it of data a one perticular
  kind of data type to an entire array.



### why numpy is important for numerical computations.

* NumPy allows complex numerical computations to be performed more efficiently than with native Python data structures.
* NumPy is used to perform data analysis and mathematical modeling in a multitude of disciplines.
* it is the backbone of scientific computing in Python, facilitating the analysis of complex data and the implementation of numerical algorithms.

### Installation of numpy

In [ ]:
numpy can be installed by command pip install numpy
we can import numpy as import numpy as np

### 2) Arrays in numpy

* An array is a data structure that can hold a fixed number of elements of the same type. 
* Arrays store multiple values in a single variable instead of declaring separate variables 
* for each value, making them powerful tools for organizing and managing data collections in programming.

### Creating arrays 

In [7]:
### for creating array we have to import numpy
import numpy as np
a= np.array([1,2,3,4]) ## create array of integers
a

array([1, 2, 3, 4])

In [11]:
b=np.array([2,'a','b','c','d',1])
b

array(['2', 'a', 'b', 'c', 'd', '1'], dtype='<U11')

## np.zeroes

## Zeroes array
* It is function in numpy that creates a new array filled with zeroes.
* syntax:numpy.zeros(shape, dtype = None, order = ‘C’) 

In [13]:
s=np.zeros(5,dtype=int)
s

array([0, 0, 0, 0, 0])

In [23]:
### creating 2D array by np.zeroes
D=np.zeros([2,3])
D

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.ones

* The numpy.ones() function returns a new array of given shape and type, filled with ones.
* Syntax: numpy.ones(shape, dtype = None) 

In [30]:
np.ones([1])

array([1.])

In [32]:
## creating 2D array with 1
np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## np.arrange

* The arange is a numpy method that return the ndarray obj containing
* every spaced value withing the given range. 

In [37]:
data=np.arange(10,20) ## creating number in between 10,20
display(data)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
arr= np.arange(5 , 10)
print(arr)

[5 6 7 8 9]


### np.linspace

*  np.linspace is a numpy function that create an array of evenly spaced number over a specific range.
*  allows you to define the start and end points of the range and the
*  number of element you want within that range....
*  By default it generate 50 linspace value creating seq range..
*  Syntax :np.linspace(start_value,end_value,num=50,endpoint=True,retstep=False,dtype=No


data=np.linspace(1,20,num=10)
data


In [46]:
data=np.linspace(1,2,num=10)
data

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [48]:
data=np.linspace(1,50,num=5)
data

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

### Array indexing

* Indexing in numpy refers to accessing and retrieving specific elements or groups of elements from an array.

In [51]:
data

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [53]:
data[0]

1.0

In [57]:
data[1]

13.25

In [59]:
data[-1]

50.0

In [61]:
a=np.random.rand(12)
print(a)

[0.63905568 0.97469441 0.44483929 0.56063925 0.93928821 0.97078644
 0.83141541 0.90911048 0.97988798 0.91323475 0.41166661 0.59226373]


In [63]:
a.reshape(4,3)
a

array([0.63905568, 0.97469441, 0.44483929, 0.56063925, 0.93928821,
       0.97078644, 0.83141541, 0.90911048, 0.97988798, 0.91323475,
       0.41166661, 0.59226373])

In [67]:
a[-1]

0.5922637296147731

### Array slicing

* Slicing in numpy refers to extracting a portion of an array byspecifying a range of indices. 
* It allows you to retrieving a subset ofthe elements from an array based on a start index,end index and step size.

In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


### Array operations

In [ ]:
The array operations include:
1) Addition
2) substraction
3) Multiplication
4) division

In [85]:
arr2=np.array([6,7,8])
arr3=np.array([5,4,3])
print(arr3)
print(arr2)

[5 4 3]
[6 7 8]


### addition of two arrays

In [87]:
arr2+arr3

array([11, 11, 11])

### Substraction of two arrays

In [89]:
arr2-arr3

array([1, 3, 5])

### Multiplication of two arrays

In [91]:
arr2*arr3

array([30, 28, 24])

## Division of two arrays

In [93]:
arr2/arr3

array([1.2       , 1.75      , 2.66666667])

### Broadcasting

* Brodcasting refers to situation in which two arrays are of different shapes and how arithmatic operations perfomed on this.

In [113]:
a2=np.array([5,6,7,8])
a3=([2.5])
a2*a3

array([12.5, 15. , 17.5, 20. ])

In [17]:
a2=np.array([5,6,7,8])
a3=([2.5])
a2/a3

array([2. , 2.4, 2.8, 3.2])

### Elementwise function and operation on array

### np.sqrt()

* numpy.sqrt(array[, out]) function is used to determine the positive square root of an array, element-wise.
* Syntax:
         np.sqrt()

In [117]:
S=np.sqrt([81,27,8,36])
S

array([9.        , 5.19615242, 2.82842712, 6.        ])

In [121]:
arr=np.array([56,45,88,144,121])
arr

array([ 56,  45,  88, 144, 121])

In [123]:
sqrt_array=np.sqrt(arr)
sqrt_array

array([ 7.48331477,  6.70820393,  9.38083152, 12.        , 11.        ])

### np.sin()

* It is  trigonometric function  which is used to calculate sin of trigonometric function.

In [126]:
B=np.array([2.5,2,8,3,4.5,6.5])
B

array([2.5, 2. , 8. , 3. , 4.5, 6.5])

In [128]:
V=np.sin(B)
V

array([ 0.59847214,  0.90929743,  0.98935825,  0.14112001, -0.97753012,
        0.21511999])

### np.exp()

* The function np.exp() is used to calculate exponential of elements in an array.

In [131]:
Z=np.exp(B)
Z

array([  12.18249396,    7.3890561 , 2980.95798704,   20.08553692,
         90.0171313 ,  665.14163304])

### 4) Array shapes and reshapes

### np.shapes()

* The np.shape()function can be defined as the number of elements in each dimension. 
* Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array.

In [138]:
arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
arr1

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [142]:
arr1.shape

(2, 4)

In [146]:
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [148]:
arr2.shape

(2, 2, 2)

### ndim()

In [ ]:
You can get the number of dimensions of a NumPy array as an integer value with the ndim attribute of ndim().

In [151]:
a_1d = np.arange(3)
print(a_1d)

[0 1 2]


In [159]:
print(a_1d.ndim)

1


In [165]:
a_2d=np.arange(10,22).reshape((4,3))
a_2d

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [167]:
print(a_2d.ndim)

2


### changing array shape

### np.reshape()

* This function give new shape to array  without changing data.

In [3]:
import numpy as np

In [5]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)


array([1, 2, 3, 4, 5, 6])

In [13]:
b=np.array([6,7,8,9])
np.reshape(b, 4)

array([6, 7, 8, 9])

### np.flatten()

* Return a copy of the array collapsed into one dimension.
* This function Converts a multi-dimensional array into a one-dimensional array by listing all elements sequentially. 
* Syntax: numpy.ndarray.flatten(order='C') 


In [27]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr=arr1.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [31]:
arr2= np.array([[12,20],[33,44]])
flat_arr1=arr2.flatten()
print(flat_arr1)


[12 20 33 44]


### np.transpose()

* The transpose of a matrix is obtained by moving the rows data to the column and columns data to the rows. 
* The numpy.transpose() function changes the row elements into column elements and the column elements into row elements.
* The output of this function is a modified array of the original one.
* Syntax:
        numpy.transpose(arr, axis=None)  

In [35]:
a= np.array([[1, 2], [4, 5], [7, 8]])  
a  
b=np.transpose(a, (1,0))  
b 

array([[1, 4, 7],
       [2, 5, 8]])

### Concatenating and splitting

### Concatenating of arrays

* This function essentially combines NumPy arrays together.
* This function is basically used for joining two or more arrays of the same shape along a specified axis
* Concatenate an arrays along the axis.
* In column-wise concatenation in both the matrix has rows must be equal
* In row-wise concatenation in both the matrix has columns must be equal.
* Syntax: numpy.concatenate((a1, a2, ...), axis)  

In [40]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y))  
z 

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [42]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y.T), axis=1)  
z  

array([[ 1,  2, 12],
       [ 3,  4, 30]])

### Splitting of arrays

* Splitting is reverse operation of Joining.
* Joining merges multiple arrays into one and Splitting breaks one array into multiple.
* We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [54]:
Arr = np.array([1, 2, 3, 4, 5, 6])
arr = np.array_split(Arr, 3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### np.vstack()

* The numpy.vstack() function is a tool in Python’s Numpy library that allows you to stack arrays vertically. 
* In simpler terms, it takes a sequence of arrays and stacks them vertically to make a single array.

In [57]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [59]:
# Create two 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a,b))
print(c)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### np.hstack()

* function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
* Syntax: np.hstack((a,b))

In [63]:
arr1 = np.array([ 1, 2, 3] ) 
print (arr1)  
  
arr2 = np.array([ 4, 5, 6] ) 
print (arr2)  
  
# Stacking the two arrays horizontally 
out_arr = np.hstack((arr1,arr2)) 
print (out_arr) 

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [65]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.hstack((a,b))
print(c)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 5) Array Manipulation

* When working with NumPy arrays it is sometimes necessary to manipulate the shape and/or size of them.
* One can for example modify the shape of an array as well as split or join arrays into new arrays.

### Indexing in multi-dimensional array

In [ ]:
* Indexing in multi-dimensional arrays is similar to indexing in lists but with multiple dimensions. 
* You specify the row and column indices.

In [70]:
array1 = np.array([[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                     
                    [[13, 14, 15, 16], 
                    [17, 18, 19, 20], 
                    [21, 22, 23, 24]]])
element = array1[1, 2, 1]
print(element) 

22


### Slicing in multi-dimensional array

* Slicing in python means taking elements from one given index to another given index.
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].
* If we don't pass start its considered 0
* If we don't pass end its considered length of array in that dimension
* This means you can extract rows, columns, or specific elements from a multi-dimensional array with ease.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the first row
row_1 = matrix[0, :]  
print(row_1)  

 # Get the second column
col_2 = matrix[:, 1] 
print(col_2)

In [76]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing a subarray
sub_matrix = matrix[0:2, 1:3]  
print(sub_matrix)

[[2 3]
 [5 6]]


In [78]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Slicing with step
sliced_matrix = matrix[::2, ::2] 
print(sliced_matrix)

[[ 1  3]
 [ 9 11]]


### Masking

* Masking is essential works with the list of Boolean values i.e, True or False 
* which when applied to an original array to return the element of interest.
* Here True refers to the value that satisfies the given condition whereas False refers to values that fail to satisfy the condition.

### Fancy indexing

* Fancy indexing is conceptually simple. 
* It means passing an array of indices to access multiple array elements at once.
* Fancy indexing can perform more advanced and efficient array operations, including conditional filtering, sorting, and so on.



In [84]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# select elements at index 1, 2, 5, 7
select_elements = array1[[1, 2, 5, 7]]
print(select_elements)

[2 3 6 8]


In [86]:
array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])
# create a list of indices to assign new values
indices = [1, 3, 6]
# create a new array of values to assign
new_values = [10, 20, 30]
# use fancy indexing to assign new values to specific elements
array1[indices] = new_values
print(array1)

[ 3 10  6 20  8  5 30  4]


### 6) Mathematical Functions

### Universal functions

* ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.
* ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
* They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

### np.add()

* In NumPy, the "universal add function" is essentially the np.add() function,
* Which performs element-wise addition between arrays, effectively acting as a universal function (ufunc) 
* That can handle arrays of different shapes due to broadcasting capabilitie
* Allowing you to add corresponding elements between multiple arrays efficiently. 

In [97]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.add(arr1, arr2) 
print(result)


[5 7 9]


### np.substract()

* numpy.subtract() function is used when we want to compute the difference of two array.It returns the difference of arr1 and arr2, element-wise.

In [100]:
a = np.array([[2, -4, 5], [-6, 2, 0]])
b = np.array([[0, -7, 5], [5, -2, 9]])
print (a)
print (b)
out_arr = np.subtract(a,b) 
print (out_arr)

[[ 2 -4  5]
 [-6  2  0]]
[[ 0 -7  5]
 [ 5 -2  9]]
[[  2   3   0]
 [-11   4  -9]]


### np.multiply()

* numpy.multiply() function is used when we want to compute the multiplication of two array. It returns the product of arr1 and arr2, element-wise.

In [103]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1 * x2

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

### Statistical functions

* Statistics involves gathering data, analyzing it, and drawing conclusions based on the information collected.
* NumPy provides us with various statistical functions that can perform statistical data analysis.

### np.mean()

* Finding the avg of an arrays.
* Syntax:
      numpy.mean(arr, axis = None)

In [109]:
arr = [20, 2, 7, 1, 34] 
print(arr)  
print(np.mean(arr)) 
   

[20, 2, 7, 1, 34]
12.8


In [111]:
a=np.array([[1,2,3],
 [2,3,4],
 [4,5,6]])
print(a)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [113]:
x=np.mean(a)
x

3.3333333333333335

### np.median()

* Compute the median of the given data (array elements) along the specified axis.
* syntax: np.median(arr, axis = None)

In [117]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [119]:
np.median(a)

3.0

### np.std()

* Compute the standard deviation of the given data (array elements) along the specified axis(if any)..
* Syntax: np.std(arr,axis=none)

In [123]:
arr = [[2, 2, 2, 2, 2],   
       [15, 6, 27, 8, 2],  
       [23, 2, 54, 1, 2, ],  
       [11, 44, 34, 7, 2]]  
np.std(arr)

15.3668474320532

In [125]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [127]:
print(np.std(a))

1.4907119849998598


### np.var()

* Compute the variance of the given data (array elements) along the specified axis(if any)
* Syntax: np.var(arr,axis=none)

In [131]:
arr = [20, 2, 7, 1, 34]  
print(np.var(arr))

158.16


In [133]:
s=np.array([[12,2000,2389465],
 [12944,41234567,233]])
s

array([[      12,     2000,  2389465],
       [   12944, 41234567,      233]])

In [135]:
np.var(s)

231433715891801.6

### np.min()

* Return the minimum of an array or minimum along an axis.
* Syntax:np.min(arr,axis=none)

In [139]:
print(s)

[[      12     2000  2389465]
 [   12944 41234567      233]]


In [145]:
print(np.min(s))

12


In [147]:
print(a)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [151]:
print(np.min(a))

1


### np.max()

* Finding max number of an arrays.
* Syntax : np.max(arr,axis=none)

In [154]:
print(s)

[[      12     2000  2389465]
 [   12944 41234567      233]]


In [156]:
np.max(s)

41234567

### Linear algebra function

In [ ]:
Numpy provide functions for linear algebra operation like matrixmultiplication(dot matrix),matrix inversion,eigvalue and more.

### np.dot()

* In Python, np.dot is a function in the NumPy library that computes the dot product of two arrays. 
* The dot product is an operation that takes two sequences of numbers of equal length and returns a single number. 
* Syntax: numpy.dot(a, b, out=None)

In [161]:
np.dot(3, 4)

12

In [173]:
a=[[1,2],[4,5]]
b=[[5,6],[8,9]]
c=np.dot(a,b)
c

array([[21, 24],
       [60, 69]])

### np.matmul()

* The numpy.matmul() function returns the matrix product of two arrays. 
* While it returns a normal product for 2-D arrays, if dimensions of either argument is >2, 
* it is treated as a stack of matrices residing in the last two indexes and is broadcast accordingly.

In [183]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [187]:
a = [[1,0],[0,1]] 
b = [1,2] 
print (np.matmul(a,b))
print (np.matmul(b,a))

[1 2]
[1 2]


### np.linalg.inv()

In [ ]:
* We use numpy.linalg.inv() function to calculate the inverse of a matrix. 
* The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [194]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print( x )
print(y )
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### np.linalg.eig()

* In Python, "np.linalg.eig" refers to a function within the NumPy library .
* That calculates the eigenvalues and corresponding eigenvectors of a square matrix.

In [197]:
mat = np.mat("1 -2;1 3") 
print(mat) 
evalue, evect = np.linalg.eig(mat) 
  
# Eigenvalues of the said matrix" 
print(evalue) 
print("") 
  
# Eigenvectors of the said matrix 
print(evect) 

[[ 1 -2]
 [ 1  3]]
[2.+1.j 2.-1.j]

[[ 0.81649658+0.j          0.81649658-0.j        ]
 [-0.40824829-0.40824829j -0.40824829+0.40824829j]]


### Random Number generation

* Python Random module generates random numbers in Python. 
* These are pseudo-random numbers means they are not truly random.
* This module can be used to perform random actions such as generating random numbers, printing random a value for a list or string, etc.
* It is an in-built function in Python.

### np.random()

* numpy.random.random() is one of the function for doing random sampling in number.
* It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).
* Syntax  :  numpy.random.random(size=None)

In [206]:
out_arr = np.random.random(size = 3) 
print ( out_arr)  

[0.22001    0.21503092 0.56664242]


### np.random.rand()

* The numpy.random.rand() function creates an array of specified shapes fills it with random values and generates random numbers with Numpy.
* Syntax:  numpy.random.rand(d0, d1, …, dn)

In [212]:
a=np.random.rand(7)
a

array([0.36362257, 0.99203832, 0.99915608, 0.58228477, 0.61087761,
       0.3756929 , 0.14680449])

In [216]:
s=np.random.rand(10)
s

array([0.88431969, 0.90210472, 0.75066788, 0.33987622, 0.18252918,
       0.16568186, 0.72936917, 0.60139457, 0.69361777, 0.05838503])

### np.random.randint()

* In Python, np.random.randint is a function within the NumPy library used to generate random integers within a specified range.
* Syntax: np.random.randint(low, high=None, size=None, dtype=int)

In [220]:
s=np.random.randint(0,5,3)
s

array([1, 1, 4])

In [226]:
a=np.random.randint(5,7,5)
a

array([5, 6, 6, 5, 5])

### Seeding random number generation

In [ ]:
* The seed() method is used to initialize the random number generator.
* The random number generator needs a number to start with (a seed value), to be able to generate a random number.

In [231]:
import random
random.seed(10)
print(random.random())

0.5714025946899135


In [233]:
random.seed("example")
print(random.random())


0.815705808134858


In [235]:
print(random.random())

0.20259898856134773


### Shuffle method

* The shuffle() method takes a sequence, like a list, and reorganize the order of the items.
* Shuffle a list (reorganize the order of the list items)
* Syntax: random.shuffle(sequence)

In [238]:
mylist = ["apple", "banana", "cherry"]
random.shuffle(mylist)

print(mylist)

['banana', 'cherry', 'apple']


### permutation in random seed

* Randomly permute a sequence, or return a permuted range.
* If x is a multi-dimensional array, it is only shuffled along its first index.
* Syntax: random.permutation(x)

In [243]:
x=np.random.permutation(10)
x

array([0, 8, 3, 2, 4, 1, 7, 9, 5, 6])

In [245]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 1, 12,  9,  4, 15])

### Broadcasting

* Broadcasting simplifies mathematical operations on arrays with different shapes. 
* It enables NumPy to efficiently apply operations element-wise without explicitly copying or reshaping data.
* It automatically adjusts the smaller array to match the shape of the larger array by replicating its values along the necessary dimensions.
* This feature reduces memory usage and eliminates the need for manual loops making code concise and computationally faster making
* It essential for handling large datasets and performing complex calculations in python

In [248]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
scalar = 10  # Scalar value

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


### Rules for broadcasting

* Broadcasting applies specific rules to determine whether two arrays can be aligned for operations:
* 1. Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
* 2. Dimension Padding: If arrays have different numbers of dimensions, the smaller array is left-padded with ones.
*3.Shape Compatibility: Two dimensions are compatible if:
* They are equal, orOne of them is 1.

In [264]:
# create 1-D array
array1 = np.array([1, 2, 3])
# create 2-D array
array2 = np.array([[1], [2], [3]])
# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2
print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
